add previous attempts

diff --git a/.github/workflows/plot_new_data.yml b/.github/workflows/plot_new_data.yml
--- a/.github/workflows/plot_new_data.yml
+++ b/.github/workflows/plot_new_data.yml
@@ -69,7 +69,7 @@ jobs:
 
         for file in ${{ steps.changed.outputs.changed }}; do
           echo "Plotting $file"
-          python main.py "$file"
+          python main.py "$file" || echo "Plotting $file failed, continuing..."
         done
 
     - name: Compress HTML in output/
